version: '3'
services:
  web:
    container_name: httpbin
    build: "httpbin"
    ports:
      - "8000:8000"
      - "8443:8443"

  app-test:
    container_name: sbt-project
    build:
      context: ../
      dockerfile: .docker/sbt-project/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - web
