version: '3'
services:
  web:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
      - "8443:443"

  app-test:
    container_name: sbt-project
    build: "sbt-project"
# Uncomment if access to the project root is required in sbt-project/Dockerfile build
#      context: ../
#      dockerfile: .docker/sbt-project/Dockerfile
    volumes:
      - ../:/app
    depends_on:
      - web
