version: '3'
services:
  web:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - "8000:8000"
      - "8443:8443"
    command:
      - sh
      - -c
      - gunicorn -b 0.0.0.0:8000 -b 0.0.0.0:8443 httpbin:app -k gevent

  app-test:
    container_name: sbt-project
    image: k3vin/sbt-java8
# Uncomment if access to the project root is required in sbt-project/Dockerfile build
#      context: ../
#      dockerfile: .docker/sbt-project/Dockerfile
    volumes:
      - ../:/app
    depends_on:
      - web
