name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker compose
      run: docker-compose -f .docker/docker-compose.yml build
    - name: Run the Docker compose
      run: docker-compose -f .docker/docker-compose.yml up -d web
    - name: Run the app
      run: docker-compose -f .docker/docker-compose.yml run app-test /app/.github/workflows/sbt-run.sh
