name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      web:
        image: kennethreitz/httpbin
        ports:
          - "8000:80"
          - "8443:443"
    
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Release
      env:
        CI_BRANCH: ${GITHUB_REF#refs/heads/}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
      run: |
        echo "Run] sbt test"
        sbt -J-Xmx2048m "; clean; coverage; test; coverageReport; coverageAggregate"
        sbt -J-Xmx2048m "; coveralls"
        echo "Run] sbt publish and release"
        sbt -J-Xmx2048m "; clean; +test; +publish"
        sbt -J-Xmx2048m "; clean; +packagedArtifacts; gitHubRelease"
